# Generated by Django 4.1.1 on 2022-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=30)),
                ('end', models.CharField(max_length=30)),
                ('seats', models.IntegerField()),
                ('balanseat', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
